config/routes.rb
Rails.application.routes.draw do
 

  root 'welcome#index'

  resources :tovar

end

app/models/tovar.rb
class Tovar < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def str_simpl str
  	result = str.gsub( /\s+/, ' ')
  	result.gsub!( /^\s/, '')
  	result.gsub!( /\s$/, '')
  	return nill unless result.size > 0
  	return result
  end

end

app/controllers/tovar_controller.rb
class TovarController < ApplicationController
  
  def index
  	@tovars = Tovar.all
  end

  def show
  	@tovar = Tovar.find( params[:id] )   	
  end

  def edit
  	@tovar = current_tovar  	
  end

  def new
  	@tovar = Tovar.new
  	@tovar.save
  	render :edit  	
  end

  def update
  	@tovar = Tovar.find( params[:id] ) 
  	@tovar.name    = str_simpl( params[:tovar][:name] )
  	@tovar.article = str_simpl( params[:tovar][:article] )	
  	@tovar.comment = str_simpl( params[:tovar][:comment] )
  	@tovar.hidden  = params[:tovar][:hidden]
    @tovar.save
  	render :show
  end

  def destroy
  	@tovar = Tovar.find( params[:id] )
  	@tovar.destroy
  	redirect_to tovar_index_path
  	
  end

  private

  def current_tovar
  	Tovar.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
	def index
	
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tovar_helper.rb
module TovarHelper
end

app/helpers/welcom_helper.rb
module WelcomHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<p><%= link_to 'Главная', root_path %> 
	&mdash;
	<%= link_to 'Товары', tovar_index_path %></p>
	
<%= yield %>

</body>
</html>

app/views/tovar/edit.html.erb
<%= form_for @tovar do |f| %>
	
	<table>
		<tr>
			<td><%= f.label 'Наименование' %></td>
			<td><%= f.text_field :name %></td>
		</tr>
		<tr>
			<td><%= f.label :article %></td>
			<td><%= f.text_field :article %></td>
		</tr>
		<tr>
			<td><%= f.label :comment %></td>
			<td><%= f.text_area :comment %></td>
		</tr>
		<tr>
			<td><%= f.label :hidden %></td>
			<td><%= f.check_box :hidden %></td>
		</tr>
		<tr>
			<td colspan="2">
				<%= f.submit %>				
			</td>
		</tr>	
	</table>

<% end %>

app/views/tovar/index.html.erb
<p>На сегодня:</p>

<table border = "1">
	<h1>
		<td>Name<td>
  		<td>Article<td>
  		<td>Comment<td>
  		<td>Created<td>
  		<td>Updated<td>  	
  		<td>Show<td>
  		<td>Edit<td>
  		<td>Delete<td>
  	</h1>
	<% @tovars.each do |tovar| %>
		<tr>
			<td><%= tovar.name %><td>
			<td><%= tovar.article %><td>
			<td><%= tovar.comment %><td>
			<td><%= tovar.created_at %><td>
			<td><%= tovar.updated_at %><td>			
			<td><%= link_to 'подробно', tovar_path( tovar ) %><td>
			<td><%= link_to 'редактировать', edit_tovar_path( tovar ) %><td>
			<td><%= link_to 'удалить', 
							tovar_path(tovar), 
							method: :delete %><td>
		<tr/>
	<% end %>
<table/>

<p><%= link_to 'добавить', new_tovar_path %><p/>

app/views/tovar/show.html.erb
<%= params %>

<%= @tovar %>
<h2>Cведения о товаре</h2>

<table border="1">
	<tr><td>Наименование</td>
		<td><%= @tovar.name %></td></tr>
	<tr><td>Артикул</td>
		<td><%= @tovar.article %></td></tr>
	<tr><td>Примечание</td>
		<td><%= @tovar.comment %></td></tr>
	<tr><td>Скрытый</td>
		<td><%= @tovar.hidden %></td></tr>
</table>

<p><%= link_to 'Редактировать', edit_tovar_path(@tovar) %></p>

<p><%= link_to 'Назад к списку', tovar_index_path %></p>

app/views/welcome/index.html.erb
<h1>The internet is a shop of clothes</h1>